// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCxoIguksj0MPuiFeXl96Ei2I3-i5PtljE',
    appId: '1:646984846130:web:f0a1b4655d10056bcfe52b',
    messagingSenderId: '646984846130',
    projectId: 'fiktur-chat-firebase',
    authDomain: 'fiktur-chat-firebase.firebaseapp.com',
    storageBucket: 'fiktur-chat-firebase.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC35pbAlcXixSbGWGi-p3k3h8Frew2w5JU',
    appId: '1:646984846130:android:c00720e98a884045cfe52b',
    messagingSenderId: '646984846130',
    projectId: 'fiktur-chat-firebase',
    storageBucket: 'fiktur-chat-firebase.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAQenjpjVCfiAVILRrG613ynbE3hLnHGus',
    appId: '1:646984846130:ios:e1b181d70b84881ccfe52b',
    messagingSenderId: '646984846130',
    projectId: 'fiktur-chat-firebase',
    storageBucket: 'fiktur-chat-firebase.appspot.com',
    iosClientId: '646984846130-schfuofsqrhbtv6qg2rmu2sip32mff9b.apps.googleusercontent.com',
    iosBundleId: 'com.example.chatUseFirebase',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAQenjpjVCfiAVILRrG613ynbE3hLnHGus',
    appId: '1:646984846130:ios:e1b181d70b84881ccfe52b',
    messagingSenderId: '646984846130',
    projectId: 'fiktur-chat-firebase',
    storageBucket: 'fiktur-chat-firebase.appspot.com',
    iosClientId: '646984846130-schfuofsqrhbtv6qg2rmu2sip32mff9b.apps.googleusercontent.com',
    iosBundleId: 'com.example.chatUseFirebase',
  );
}
